agents:
  queue: "public"

steps:
- name: "Go build and test %n"
  command: make
  plugins:
    - docker-compose#v3.7.0:
        run: app

- name: "Check licenses %n"
  command: make licensed
  plugins:
    - docker-compose#v3.7.0:
        run: licensing

- wait

- block: ":rocket: Release !"
  branches: "main"

- command: script/bump-version.sh
  if: build.branch == "main"
  label: ":arrow_up_small: Bump & tag version"

- wait

- label: ":github: Publishing artifacts"
  if: build.branch == "main"
  command: script/release.sh
  plugins:
    - docker#v3.8.0:
        image: "golang:1.17"
        propagate-environment: true
        environment:
          - "GITHUB_TOKEN"
          - "DOCKER_USERNAME"
          - "DOCKER_PASSWORD"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
