name: licensed-ci

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git private repo access
        env:
          GITHUB_TOKEN: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
        run: |
          git config --global --add url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install licensed
        uses: jonabc/setup-licensed@v1
        with:
          version: 2.x

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Run licensed
        id: licensed
        uses: jonabc/licensed-ci@v1
        with:
          github_token: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}

      - name: Report licensed activity
        uses: actions/github-script@0.2.0
        if: always() && steps.licensed.outputs.pr_number
        with:
          github-token: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.licensed.outputs.pr_number }},
              body: 'licensed has detected incompatible changes'
            })
